### PR TITLE
oui module: add local/multicast bit parsing, plus nmap-mac-prefixes backend

### PR DESCRIPTION
**Pull request by Habbie**
also adds tests

### CODE REVIEW

**Comment by teunvink** [comment]
AMS-IX ARP sponge: `c6:17:44:26:e8:87`

**Comment by Habbie** [comment]
> AMS-IX ARP sponge: `c6:17:44:26:e8:87`

teun found this empirically - it's also documented at https://www.ams-ix.net/ams/documentation/more

**Comment by teunvink** [comment]
LINX: `00:1b:21:5f:2e:35`

**Comment by teunvink** [comment]
DE-CIX: `0a:bf:a1:10:00:00`

**Comment by Habbie** [comment]
amsix, linx, decix pushed

**Comment by Habbie** [comment]
current bot does ` macaddr = re.sub('[^A-F0-9\:]', '', macaddr)` instead of dropping `:` and `-` explicitly

**Comment by Habbie** [comment]
via teun, could do `requests.get(..).json()` and catch the exception, instead of checking for `{`

**Comment by Habbie** [comment]
> current bot does ` macaddr = re.sub('[^A-F0-9\:]', '', macaddr)` instead of dropping `:` and `-` explicitly

done

also added a few features stolen from the gozerbot oui, like multicast IPs for v4 and v6

**Comment by sndrsmnk** [comment]
Thanks!

**Pull request merged**
